contactForm/urls.py
from django.urls import path

from . import views

app_name = 'contactForm'
urlpatterns = [
	path('', views.index, name='index'),
	path('submitted/', views.submitted, name='submitted')
]

djangoWebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('contactForm/',include('contactForm.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

website/urls.py
from django.urls import include, path

from . import views

app_name = 'website'
urlpatterns = [
	path('', views.index, name='index'),
	path('results', views.results, name='results'),
	path('accounts/', include('django.contrib.auth.urls')),
	path('data/', views.data, name='data'),
	path('user/', views.user, name='user')
]

contactForm/models.py
# Database Models
from django.db import models

# validation
from django.core.validators import validate_email

# django utilities
from django.utils import timezone

# Create your models here.

HELP_TYPE = (
	('Help', 'Help'),
	('Bug Report', 'Bug Report'),
	('Just Saying Hi!', 'Just Saying Hi!'),
	('Request Access', 'Request Access')
)


class ContactForm(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	middle_name = models.CharField(max_length=50, blank=True)
	cell_phone = models.CharField(max_length=20)
	home_phone = models.CharField(max_length=20,blank=True)
	email = models.CharField(max_length=50, validators=[validate_email])
	message = models.TextField(blank=False,default='')
	help_type = models.CharField(max_length=20, choices=HELP_TYPE, blank=False, default='Help')
	created_date = models.DateTimeField(default=timezone.now)

website/models.py
from django.db import models

# Create your models here.

contactForm/forms.py
# Forms
from django import forms

# models
from .models import ContactForm

# Validation
from django.core.validators import validate_email


class ContactForm(forms.ModelForm):

	class Meta:
		model = ContactForm
		fields = ('first_name', 'middle_name', 'last_name', 'cell_phone', 'home_phone', 'email', 'help_type', 'message')

contactForm/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import ContactForm

# logging
import logging

logger = logging.getLogger(__name__)

# Create your views here.


def index(request):

	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			context = {
				'message': 'Form Saved Successfully',
				'nbar': 'Contact'
			}
			return HttpResponseRedirect(reverse('contactForm:submitted'), context)
	else:
		form = ContactForm()
	context = {
		'form': form,
		'nbar': 'Contact'
	}
	return render(request, 'contactForm/index.html', context)


def submitted(request):
	context = {
		'nbar': 'Contact'
	}
	return render(request, 'contactForm/submitted.html', context)

website/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse

# Authentication
from django.contrib.auth import authenticate, login

# models
from django.apps import apps
from django.db.models import Count

contactForm = apps.get_model('contactForm', 'ContactForm')

# Create your views here.


def index(request):
	context = {
		'nbar': 'Home'
	}
	return render(request, 'index.html', context)


def results(request):
	context = {
		'nbar': 'Results'
	}
	return render(request, 'results.html', context)


def data(request):
	data = contactForm.objects.values('help_type').annotate(values=Count('first_name'))
	return JsonResponse({'data': list(data)})

def user(request):
	data = contactForm.objects.values('first_name').annotate(values=Count('first_name'))
	return JsonResponse({'data': list(data)})

contactForm/templates/contactForm/index.html
{%  extends 'base.html' %}

{%  block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    <h4>
    Thank you for contacting us!  Please fill out the form below including the reason for your message
    </h4>
    <br />
    <form method="POST">
        {%  csrf_token %}
        {% for field in form %}
            <span style="vertical-align: top;">{{ field.label }}{% if field.field.required %}<span style="color: red; vertical-align: top;">*</span>{% endif %}</span>
            {{ field }}
            {% if field.errors %}
                <br />
                <span style="color: red;">{{ field.errors.as_text }}</span>
            {% endif %}
            <br /><br />
        {%  endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{%  endblock %}

contactForm/templates/contactForm/submitted.html
{%  extends 'base.html' %}

{%  block content %}
<h1>Form submitted successfully!</h1>
{% endblock %}

website/templates/base.html
{%  load staticfiles %}
{%  load website_extras %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" />

    <title>BBisesti Example Website</title>

    <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css' %}" />


      <style type="text/css">
        body {
          padding-top: 5rem;
        }
      </style>

  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">BBisesti Example Website</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if nbar == 'Home' %}active {% endif %}">
            <a class="nav-link" href="{% url 'website:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if request.user|has_group:"resultsViewer" %}
                <li class="nav-item {% if nbar == 'Results' %}active {% endif %}">
                    <a class="nav-link" href="{% url 'website:results' %}">Results</a>
                </li>
            {% endif %}
          <li class="nav-item {% if nbar == 'Contact' %}active {%  endif %}">
              <a class="nav-link" href="{%  url 'contactForm:index' %}">Contact Us</a>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:index' %}">Welcome, {{ user.first_name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-info" href="{% url 'logout' %}">Logout</a>
                </li>
            {% endif %}
            {% if request.user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="content container">
        <div class="row" style="text-align: center">
            <span class="col-md-2"></span>
            <div class="col-md-8">
                {% block content %}
                {%  endblock %}
            </div>
            <span class="col-md-2"></span>
        </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{%  static 'js/popper.min.js' %}" type="text/javascript"></script>
    <script src="{%  static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

    {# for Chart JS #}
    <script src="{% static 'js/Chart.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/chart.js' %}" type="text/javascript"></script>
  </body>
</html>

website/templates/index.html
{%  extends 'base.html' %}

{%  block content %}
    <h4>Welcome to Brett Bisesti's Example Website!</h4>
    <br />
    <p>If you login to the application you should see a page which summarizes all of the contact form submissions</p>
{%  endblock %}

website/templates/results.html
{%  extends 'base.html' %}
{% load static %}

{%  block content %}
    <h3>Contact Form Results</h3>

    <br />

    <div class="row">
        <div class="col-md-6">
            <h4>Here is a breakdown of responses by type</h4>
            <canvas style="display: none;" id="resultsPieChart" width="500px" height="400px"></canvas>
        </div>
        <div class="col-md-6">
            <h4>Here is a breakdown of responses by user</h4>
            <canvas style="display: none;" id="userPieChart" width="500px" height="400px"></canvas>
        </div>
    </div>

    <br />
    <h4 id="errorMessage" style="display: none; color: green;"></h4>



{%  endblock %}